# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

from .NEM2EmbeddedTransaction import NEM2EmbeddedTransaction

if __debug__:
    try:
        from typing import Dict, List, Optional
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        Dict, List, Optional = None, None, None  # type: ignore


class NEM2AggregateCompleteTransaction(p.MessageType):

    def __init__(
        self,
        transactions: List[NEM2EmbeddedTransaction] = None,
    ) -> None:
        self.transactions = transactions if transactions is not None else []

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('transactions', NEM2EmbeddedTransaction, p.FLAG_REPEATED),
        }
